### ISSUE TITLE
Demo App Crashes

### ISSUE THREAD

**Issue by Sun3** [nofelmahmood/CKSIncrementalStore#1]
When you run the app I receive an error in the CKIncrementalStore.swift for function triggerSync() on below line:

'''
...
if error == nil
            {
                print("Sync Performed Successfully")
                NSOperationQueue.mainQueue().addOperationWithBlock({ () -> Void in

// CRASHES ON THIS LINE EVERY TIME                    NSNotificationCenter.defaultCenter().postNotificationName(CKSIncrementalStoreDidFinishSyncOperationNotification, object: self)

```
            })
        }
```

...
'''

When I comment that line out the app does not crash but syncing stops. 

I also needed to add to the TableView a cell otherwise code crashes.

Thank you.

**Comment by nofelmahmood** [comment]
Did you enable CloudKit for your app ?

**Comment by nofelmahmood** [comment]
Do you have a developer account and iCloud enabled in the Demo App ?

**Comment by Sun3** [comment]
Yes, I changed the domain com.name... and enabled iCloud. When I comment out that line I am able to create records but will not sync with other devices until I re-enable but then it crashes.

**Comment by nofelmahmood** [comment]
ok Thanks. I am checking the demo app.

**Comment by nofelmahmood** [comment]
Thanks for pointing out the error .  Check now I updated it ! The demo works for me :)
btw I had no crashes on the triggerSync() method and the sync is working now.

**Comment by Sun3** [comment]
Yep, no more crash. Great job...

**Comment by nofelmahmood** [comment]
Thanks man ! :)

**Comment by Sun3** [comment]
Quick Question:  I created a new project MyNotes SplitView with CoreData and added the CKIncrementalStore.swift and adopted the CoreDataStack.swift

In my Core Data I have a Class called Event with two fields timeStamp and note. Before integrating the CKIncrementalStore I can create local Core Data files.

Once I implement the CKIncrementalStore I receive below error when trying to add a new record.

```
2015-06-22 19:37:46.803 MyNotes[9790:427654] CoreData: error: Serious application error.  Exception was caught during Core Data change processing.  This is usually a bug within an observer of NSManagedObjectContextObjectsDidChangeNotification.  [<MyNotes.Event 0x7fceb85b5490> valueForUndefinedKey:]: the entity Event is not key value coding-compliant for the key "cks_LocalStore_Attribute_ChangeType". with userInfo {
    NSTargetObjectUserInfoKey = "<MyNotes.Event: 0x7fceb85b5490> (entity: Event; id: 0x7fceb85a8c50 <x-coredata:///Event/t7CA54E5E-46A2-46AF-A500-BC7DE2D8A00A2> ; data: {\n    note = \"YES - 2015-06-22 23:37:46 +0000\";\n    timeStamp = \"2015-06-22 23:37:46 +0000\";\n})";
    NSUnknownUserInfoKey = "cks_LocalStore_Attribute_ChangeType";
}
2015-06-22 19:37:46.818 MyNotes[9790:427654] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<MyNotes.Event 0x7fceb85b5490> valueForUndefinedKey:]: the entity Event is not key value coding-compliant for the key "cks_LocalStore_Attribute_ChangeType".'
```

Any ideas?

**Comment by nofelmahmood** [comment]
Its best if you consider starting with the demo app.

**Comment by Sun3** [comment]
Yep, I have the demo app working great. I was trying to create a new project and see how it would work.

**Comment by Sun3** [comment]
Do you think I am missing a step? 
1. Create a SplitView Core Data iOS app
2. Add CloudKit
3. Add field to Event entity called note
4. Create a NSManagedObject Class for Event
5. In MasterViewController.swift Change insertNewObject to use Event Class
6. Run App and I can create new entries without errors.
7. Add CKIncrementalStore.swift to project
8. AppDelegate change persistentStoreCoordinator() to use CKIncrementalStore
9. MasterViewControler.swift add Notification syncFinished
10. Run and add Record and receive ERROR

```
2015-06-22 21:22:39.144 MyNotes[1031:29993] CoreData: error: Serious application error.  Exception was caught during Core Data change processing.  This is usually a bug within an observer of NSManagedObjectContextObjectsDidChangeNotification.  [<MyNotes.Event 0x7fd7fc101230> valueForUndefinedKey:]: the entity Event is not key value coding-compliant for the key "cks_LocalStore_Attribute_ChangeType". with userInfo
```

Did I miss any steps to integrate the lib?

Thanks.

**Comment by nofelmahmood** [comment]
The problem is that when u first ran the app it created the store file and next time when u change the store type to CKSIncrementalStore it tries to reuse that file while CKSIncrementalStore does some model changes at the backend to create the new sqlite file.
In short delete the app and run it again but this time set the store type to CKSIncrementalStore first.

**Comment by Sun3** [comment]
Sorry, I forgot to place that step :) but I do delete it before I run it with same results.

**Comment by nofelmahmood** [comment]
If that's the case then the demo shoudn’t actually work. Kindly check your CoreData stack with any possible errors. 
If you copied the code from the CoreDataStack class from the demo, then you might have missed a few things that need to be changed like Model name etc. 
Best is to copy the CoreData Stack Methods from the app delegate into your CoreDataStack class and then set the store type to CKSIncrementalStore. 
I don't think it's a logical error, I can't possibly help you with this particular problem.

**Comment by Sun3** [comment]
Thanks...

ps: I wanted to update you that the error was Apple's pre-written UITableView Core Data code causing the issue.

**Comment by nofelmahmood** [comment]
Thanks :)
