### ISSUE TITLE
Object not saved correctly

### ISSUE THREAD

**Issue by emilagervigstarup** [nofelmahmood/CKSIncrementalStore#12]
Object not saved correctly.

My steps:
First I create a client it works fine.
Then I create a project but the project is not saved correctly, it appears until I close and open the app. Then its gone.
The project is not synced to the cloud kit either. Thats an fail I haven’t seen before. It works local with coredata and it doesn't give me any error.
So It can be hard to debug :(

**Comment by nofelmahmood** [comment]
Let me check :)
