### ISSUE TITLE
Externally stored binary data should be attached to the record as CKAsset.

### ISSUE THREAD

**Issue by saschaholesch** [nofelmahmood/CKSIncrementalStore#13]
Support for binary data stored in CoreData with the option "Allows external storage" enabled on the attribute would be great. Commonly, storing big amounts of binary data inside the data store is not desirable.

![screenshot_122](https://cloud.githubusercontent.com/assets/776284/9002896/077b8b3e-37a4-11e5-8d4e-a83986870c6c.png)

**Comment by nofelmahmood** [comment]
Yes, you are absolutely right. It's a great feature. Look forward to work on it once I am finished with upgrading the project to support swift 2.0 :)

**Comment by fila95** [comment]
Do you have some news about this new feature?

**Comment by skydivedan** [comment]
Just curious about this feature as well.
