### ISSUE TITLE
Manual attaching of CKAssets to a record

### ISSUE THREAD

**Issue by saschaholesch** [nofelmahmood/CKSIncrementalStore#14]
It is best practice to store big blobs of data (such as images) on the filesystem. An interface to add CKAssets to records would be desirable.

Since the CKSRecordContext is holding all records, the user could manually attach CKAssets to records before calling save() on it. Maybe even an automated option might be possible (e.g. if there is a file path stored in an attribute, a CKAsset could be created)?

**Comment by nofelmahmood** [comment]
Any thing related to CKSRecordContext should be discussed on an issue belonging to that repository. Kindly if you have any questions about it its advisable to open an issue over [here](https://goo.gl/wfu3Oy). :)

**Comment by saschaholesch** [comment]
I recreated it in the CKSRecordContext repository. I was not aware this was a separate project, sorry.

**Comment by nofelmahmood** [comment]
No problem :)
