### ISSUE TITLE
WatchOS2 support!

### ISSUE THREAD

**Issue by acegreen** [nofelmahmood/CKSIncrementalStore#16]
With the current implementation there is no way to sync with the Apple watch app. It would be great if we found a way to do it. As off WatchOS2, there are two stores now, so this library would be in great demand if it works with the watch app

**Comment by nofelmahmood** [comment]
Great. I am already thinking of digging into Watch Connectivity to find the right answers and then do whatever is required to support it. Stay tuned :)

**Comment by acegreen** [comment]
Thats great to hear :)

**Comment by acegreen** [comment]
@nofelmahmood So in my option Watch Connectivity API is bullshit. applicationContext will only accept dictionary of property list values. That means you can't pass a custom class NSManagedObject without serializing it then back. 

So we went from a shared core data store, to two separate ones and no good way to pass data between them. if you library can fix that, you are golden. Especially because it not only fixes that but syncs all stores using cloud kit.

**Comment by nofelmahmood** [comment]
@acegreen Sorry to hear that. I really appreciate that how you are contributing to making this library more awesome. Huge Kudos from me for that. 
Yes it looks like you are right on this, that if we are able to solve the problem of passing data between the two stores, rest is already handled in the library. I assure you that I'l look in to it once I am able to find time. 
I am already fixing and improving some other stuff in the library. I first look forward to make it mature to a level that it actually ships in an iOS or Mac app on the App Store. Once that is done next is Watch !
Thanks again for your interest and valuable feedback :)

**Comment by acegreen** [comment]
@nofelmahmood No worries at all! I think this library has huge potential and you have done some amazing work. Glad to see you working hard on this project and ill definitely be one of its users. 

Keep us updated on your progress. I think many are watching :)

**Comment by acegreen** [comment]
@nofelmahmood So this is what I was able to cobble together

 http://recordit.co/tpptAj3w24

**Comment by acegreen** [comment]
@nofelmahmood Any progress on this?
