### ISSUE TITLE
NSData Attribute Sync Crash

### ISSUE THREAD

**Issue by fila95** [nofelmahmood/CKSIncrementalStore#17]
I've got my nsmanagedobject subclass which has also an nsdata attribute to store an image. That's not always needed and so when i set it to nil Seam Crashes.
Look at the screenshot below..
Hope in a fix..
Best regards
<img width="889" alt="schermata 2015-08-26 alle 12 01 55" src="https://cloud.githubusercontent.com/assets/7265334/9490751/4a4f1b88-4bea-11e5-9e4f-34e84bf10408.png">

**Comment by nofelmahmood** [comment]
Check now :)

**Comment by fila95** [comment]
ok thanks ;)

**Comment by nofelmahmood** [comment]
**Tip when using NSData in Seam**
You should store pictures as a CKAsset. For a CKRecord there is a size limitation. For a CKAsset there is not (beside the CloudKit storage limitations). According to the documentation:

Use assets for discrete data files. When you want to associate images or other discrete files with a record, use a CKAsset object to do so. The total size of a record’s data is limited to 1 MB though assets do not count against that limit.

Seam doesn't support CKAsset as for now. But this feature is in works. Follow [this issue](https://github.com/nofelmahmood/Seam/issues/13) to find out when it gets done.
