### ISSUE TITLE
SeamDemo infinite loop

### ISSUE THREAD

**Issue by rbugajewski** [nofelmahmood/CKSIncrementalStore#18]
SeamDemo runs in an infinite loop, consumes more and more memory, until it finally crashes.

Steps to reproduce:
1. Download the current master branch.
2. Change the Bundle Identifier in the SeamDemo project to something unique.
3. Add a custom iCloud container and select it as the only one to use.
4. Run the app either in the simulator or on an device.

I expect the app to normally run, and not to sync anything until I create a first record. I use the latest iOS 9, OS X 10.11 & Xcode 7 betas. Currently I just get the following output until the demo app crashes:

```
Sync Started
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
More Coming
…
```

On inspecting `~/Library/Mobile Documents/` I don’t see the corresponding subfolder created by Apple’s frameworks which is normally present when you use Core Data + iCloud and I don’t see any data in the CloudKit Dashboard.

**Comment by apoorvmote** [comment]
go to SMStore.swift file 

in load metadata method. In backingMOM != 0 code. After self.operationQueue!.maxConcurrentOprationCount =1 line

add self.triggerSync()

**Comment by philippherzig** [comment]
I have the same problem with a osx app. It's working without problems on ios.
