### ISSUE TITLE
Cocoapods can't find Seam pod

### ISSUE THREAD

**Issue by koenvanderdrift** [nofelmahmood/CKSIncrementalStore#20]
My Podfile can't find it, and this page gives a 404 error: https://github.com/CocoaPods/Specs/tree/master/Specs/Seam

What am I missing?

**Comment by nofelmahmood** [comment]
Sorry! Check it now :)

**Comment by koenvanderdrift** [comment]
Got it!

I think you have a typo in your email in the podfile, though :)
