### ISSUE TITLE
TVOS support 

### ISSUE THREAD

**Issue by marcorm** [nofelmahmood/CKSIncrementalStore#28]
Support for TVOS framework would be great, especially because on TVOS Core Data is not guaranteed to be persistent.

**Comment by nofelmahmood** [comment]
tvOS does not provide persistent local storage while Seam uses a SQLITE CoreData store to persist data locally. 
Scroll down to the heading **Local Storage for Your App Is Limited** in [tvOS Programming Guide](https://developer.apple.com/library/tvos/documentation/General/Conceptual/AppleTV_PG/)

**Comment by marcorm** [comment]
Thanks for the answer Nofel, actually tvos supports coredata SQLite storage. But it places the database instance in the Cache folder. So the OS coul delete it every time, when the app is not running.

Could your library be useful in this use case?

Thank you again
Best regards

Marco Marinangeli

**Comment by chbeer** [comment]
How It makes more sense: sync on iOS and OS X via Seam and access CloudKit directly from appleTV.

Imagine a user would like to use your app and that needs to sync before it's ready to use. Sync is not suitable for appleTV.
