### ISSUE TITLE
Swift 2.0 Support 

### ISSUE THREAD

**Issue by nofelmahmood** [nofelmahmood/CKSIncrementalStore#5]
Created a new branch for Swift 2.0

**Comment by acegreen** [comment]
0.5.2 is Swift 2.0 ready?

<img width="545" alt="screen shot 2015-08-13 at 10 53 20 pm" src="https://cloud.githubusercontent.com/assets/10794609/9266373/3108d08c-420e-11e5-884d-6659840a1036.png">

**Comment by nofelmahmood** [comment]
try this in your pod file :)

pod 'CKSIncrementalStore', :git => 'https://github.com/nofelmahmood/CKSIncrementalStore.git', :commit => 'c78ca31'
