### ISSUE TITLE
'Cannot retrieve referenceObject from an objectID that was not created by this store’ error

### ISSUE THREAD

**Issue by emilagervigstarup** [nofelmahmood/CKSIncrementalStore#6]
I have  an object called Client, which have a NSSet of Projects and the Project object have a Client reference.

I can create a client and edit it as long as it dosen’t have any projects.
But when I create a project and give the project a client. I can’t edit the client anymore.
Is gives me this error: 'Cannot retrieve referenceObject from an objectID that was not created by this store’

```
                managedContext.refreshObject(client, mergeChanges: false)
                for pro in client.projects {
                    managedContext.refreshObject(pro as! Project, mergeChanges: false)
                }
```

If I call the refresh method show above I dont get the earlier error but this:

Error Domain=NSCocoaErrorDomain Code=1550 "The operation couldn’t be completed. (Cocoa error 1550.)" UserInfo=0x1740ec100 {NSValidationErrorObject=<TimeTarget.Client: 0x1700bbfc0> (entity: Client; id: 0x170424720 x-coredata://EC349C9D-E6A5-4297-9B96-778618D88B0E-7984-000002915A9F1799/Client/pBA63AEE6-5C27-47A3-86B0-57FD57A8A1EE ; data: {
    billable = 0;
    color = 0;
    defaultHourRate = 0;
    name = Huhu4;
    projects =     (
        "0xd000000000040002 x-coredata://8B9AF010-A46F-4A5B-872B-A87B38C291C5/Project/p1"
    );
}), NSValidationErrorValue=Relationship 'projects' on managed object (0x1700bbfc0) <TimeTarget.Client: 0x1700bbfc0> (entity: Client; id: 0x170424720 x-coredata://EC349C9D-E6A5-4297-9B96-778618D88B0E-7984-000002915A9F1799/Client/pBA63AEE6-5C27-47A3-86B0-57FD57A8A1EE ; data: {
    billable = 0;
    color = 0;
    defaultHourRate = 0;
    name = Huhu4;
    projects =     (
        "0xd000000000040002 x-coredata://8B9AF010-A46F-4A5B-872B-A87B38C291C5/Project/p1"
    );
}) with objects {(
    <TimeTarget.Project: 0x1700de060> (entity: Project; id: 0xd000000000040002 x-coredata://8B9AF010-A46F-4A5B-872B-A87B38C291C5/Project/p1 ; data: {
    billable = nil;
    "cks_LocalStore_Attribute_ChangeType" = 0;
    "cks_LocalStore_Attribute_EncodedValues" = <62706c69 73743030 d4010203 04050649 4a582476 65727369 6f6e5824 6f626a65 63747359 24617263 68697665 72542474 6f70>;
    "cks_LocalStore_Attribute_RecordID" = "5C8A7045-6398-441F-B3D1-46A30523C4D7";
    client = "0xd000000000040000 x-coredata://8B9AF010-A46F-4A5B-872B-A87B38C291C5/Client/p1";
    color = 0;
    defaultHourRate = 0;
    name = Nu;
})
)}, NSValidationErrorKey=projects, NSLocalizedDescription=The operation couldn’t be completed. (Cocoa error 1550.)}

Everything works if I dont use CKSIncrementalStore and only core data local on iPhone.

My core data model:
<img width="473" alt="screen shot 2015-07-19 at 00 31 52" src="https://cloud.githubusercontent.com/assets/3866442/8763761/965470ec-2dad-11e5-8e71-6efe838947a0.png">

**Comment by nofelmahmood** [comment]
Kindly check the latest version now and post the feedback here :)

**Comment by emilagervigstarup** [comment]
It works for client and projects :)
But then I added timeEntries object and are getting this error:

Error Domain=NSCocoaErrorDomain Code=1550 "The operation couldn’t be completed. (Cocoa error 1550.)" UserInfo=0x1700fc480 {NSValidationErrorObject=<TimeTarget.Client: 0x1742a7e00> (entity: Client; id: 0x174625500 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Client/p6EB445B3-EDE4-4F7C-91AB-5321CA1D8C12 ; data: {
    billable = 0;
    color = 0;
    defaultHourRate = 0;
    name = Kkkk;
    projects =     (
        "0x170434100 x-coredata:///Project/t978835D4-6FCD-46AD-8135-7C1404A347F82",
        "0x1746249a0 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Project/pF673936A-2E2E-400A-8B84-D26D6A2B97D6",
        "0x174626a00 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Project/p8FDD274C-68E0-4781-A844-4FE8C0F9F30B"
    );
}), NSValidationErrorValue=Relationship 'projects' on managed object (0x1742a7e00) <TimeTarget.Client: 0x1742a7e00> (entity: Client; id: 0x174625500 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Client/p6EB445B3-EDE4-4F7C-91AB-5321CA1D8C12 ; data: {
    billable = 0;
    color = 0;
    defaultHourRate = 0;
    name = Kkkk;
    projects =     (
        "0x170434100 x-coredata:///Project/t978835D4-6FCD-46AD-8135-7C1404A347F82",
        "0x1746249a0 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Project/pF673936A-2E2E-400A-8B84-D26D6A2B97D6",
        "0x174626a00 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Project/p8FDD274C-68E0-4781-A844-4FE8C0F9F30B"
    );
}) with objects {(
    <TimeTarget.Project: 0x1702b9f80> (entity: Project; id: 0x170434100 x-coredata:///Project/t978835D4-6FCD-46AD-8135-7C1404A347F82 ; data: {
    billable = 0;
    client = "0x174625500 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Client/p6EB445B3-EDE4-4F7C-91AB-5321CA1D8C12";
    color = 0;
    defaultHourRate = 0;
    name = Ikk;
    timeEntries =     (
    );
}),
    <TimeTarget.Project: 0x1740d5460> (entity: Project; id: 0x1746249a0 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Project/pF673936A-2E2E-400A-8B84-D26D6A2B97D6 ; data: {
    billable = 0;
    "cks_LocalStore_Attribute_ChangeType" = nil;
    "cks_LocalStore_Attribute_EncodedValues" = nil;
    "cks_LocalStore_Attribute_RecordID" = nil;
    client = "0xd000000000080000 x-coredata://08A6D6A1-D808-4CB5-9707-718328D28597/Client/p2";
    color = 0;
    defaultHourRate = 0;
    name = Jjj;
    timeEntries = "<relationship fault: 0x170435ec0 'timeEntries'>";
}),
    <TimeTarget.Project: 0x1740d55b0> (entity: Project; id: 0x174626a00 x-coredata://8BFB4997-9AC6-4F9D-8349-D4BFDD02B6D4-8593-000002ABBE3D0C8E/Project/p8FDD274C-68E0-4781-A844-4FE8C0F9F30B ; data: {
    billable = 0;
    "cks_LocalStore_Attribute_ChangeType" = nil;
    "cks_LocalStore_Attribute_EncodedValues" = nil;
    "cks_LocalStore_Attribute_RecordID" = nil;
    client = "0xd000000000080000 x-coredata://08A6D6A1-D808-4CB5-9707-718328D28597/Client/p2";
    color = 0;
    defaultHourRate = 0;
    name = Kk;
    timeEntries = "<relationship fault: 0x170438f20 'timeEntries'>";
})
)}, NSValidationErrorKey=projects, NSLocalizedDescription=The operation couldn’t be completed. (Cocoa error 1550.)}

Again it works without CKSIncrementalStore.
My new core data model is:
<img width="538" alt="screen shot 2015-07-19 at 01 18 46" src="https://cloud.githubusercontent.com/assets/3866442/8763890/1f1e4122-2db4-11e5-9773-68432c8cc9c9.png">

I did a reset on cloud kit and deleted the app on iPhone when I changed the model.

**Comment by emilagervigstarup** [comment]
First time I build a clean app I can add and edit clients, projects and time entries. But when I close and reopen the app the error appears when I try to edit anything. :)

**Comment by nofelmahmood** [comment]
Check again :)

**Comment by emilagervigstarup** [comment]
Thanks man, it works great now :)

**Comment by nofelmahmood** [comment]
No problem. I am glad I was able to help :)

**Comment by emilagervigstarup** [comment]
I was to early to close :(

When I try to edit and TimeEntry i get this error:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship: property = "project"; desired type = TimeTarget.Project; given type = TimeTarget.Project; value = <TimeTarget.Project: 0x1740df6b0> (entity: Project; id: 0x174426160 x-coredata://6B81EA38-15B7-4C85-ADB5-6640EE31DF5D-9088-000002BEECC9720D/Project/p254230CF-A9CD-4CAD-B47F-19DFBA054081 ; data: {
    billable = 0;
    "cks_LocalStore_Attribute_ChangeType" = nil;
    "cks_LocalStore_Attribute_EncodedValues" = nil;
    "cks_LocalStore_Attribute_RecordID" = nil;
    client = "0x174239480 x-coredata://6B81EA38-15B7-4C85-ADB5-6640EE31DF5D-9088-000002BEECC9720D/Client/p686DBB54-ACC5-4313-8369-2DF9B8003E4B";
    color = 0;
    defaultHourRate = 0;
    name = Kk;
    timeEntries = "<relationship fault: 0x17442da40 'timeEntries'>";
}).'

And same when I try an edit an Project:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship: property = "client"; desired type = TimeTarget.Client; given type = TimeTarget.Client; value = <TimeTarget.Client: 0x1702afc00> (entity: Client; id: 0x174621ac0 x-coredata://17D56827-FF19-4DDD-8161-E4C930BC4398-9102-000002BF85C10C71/Client/p686DBB54-ACC5-4313-8369-2DF9B8003E4B ; data: {
    billable = 0;
    color = 0;
    defaultHourRate = 0;
    name = Klkj;
    projects =     (
        "0x170432e00 x-coredata://17D56827-FF19-4DDD-8161-E4C930BC4398-9102-000002BF85C10C71/Project/p9E6EA418-FF51-492C-84ED-575A76659490",
        "0x170432e20 x-coredata://17D56827-FF19-4DDD-8161-E4C930BC4398-9102-000002BF85C10C71/Project/p254230CF-A9CD-4CAD-B47F-19DFBA054081"
    );
}).'

The client I can edit / save without problem. And same as before It first happens when I have closed the app and reopened the app again.

**Comment by nofelmahmood** [comment]
Kindle close this issue. This is a different error, post this as another issue and we can discuss it over there :)
