### ISSUE TITLE
Unacceptable type of value for to-one relationship

### ISSUE THREAD

**Issue by emilagervigstarup** [nofelmahmood/CKSIncrementalStore#7]
When I try to edit and TimeEntry i get this error:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship: property = "project"; desired type = TimeTarget.Project; given type = TimeTarget.Project; value = (entity: Project; id: 0x174426160 x-coredata://6B81EA38-15B7-4C85-ADB5-6640EE31DF5D-9088-000002BEECC9720D/Project/p254230CF-A9CD-4CAD-B47F-19DFBA054081 ; data: {
billable = 0;
"cks_LocalStore_Attribute_ChangeType" = nil;
"cks_LocalStore_Attribute_EncodedValues" = nil;
"cks_LocalStore_Attribute_RecordID" = nil;
client = "0x174239480 x-coredata://6B81EA38-15B7-4C85-ADB5-6640EE31DF5D-9088-000002BEECC9720D/Client/p686DBB54-ACC5-4313-8369-2DF9B8003E4B";
color = 0;
defaultHourRate = 0;
name = Kk;
timeEntries = "";
}).'

And same when I try an edit an Project:
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for to-one relationship: property = "client"; desired type = TimeTarget.Client; given type = TimeTarget.Client; value = (entity: Client; id: 0x174621ac0 x-coredata://17D56827-FF19-4DDD-8161-E4C930BC4398-9102-000002BF85C10C71/Client/p686DBB54-ACC5-4313-8369-2DF9B8003E4B ; data: {
billable = 0;
color = 0;
defaultHourRate = 0;
name = Klkj;
projects = (
"0x170432e00 x-coredata://17D56827-FF19-4DDD-8161-E4C930BC4398-9102-000002BF85C10C71/Project/p9E6EA418-FF51-492C-84ED-575A76659490",
"0x170432e20 x-coredata://17D56827-FF19-4DDD-8161-E4C930BC4398-9102-000002BF85C10C71/Project/p254230CF-A9CD-4CAD-B47F-19DFBA054081"
);
}).'

The client I can edit / save without problem. It first happens when I have closed the app and reopened the app again.

Model:
<img width="538" alt="1f1e4122-2db4-11e5-9773-68432c8cc9c9" src="https://cloud.githubusercontent.com/assets/3866442/8764064/b923e3ea-2dbd-11e5-9d60-d09264397b78.png">

**Comment by nofelmahmood** [comment]
[This](http://stackoverflow.com/questions/16711160/unacceptable-type-of-value-for-to-one-relationship-desired-type-nsmanagedobje) might help.

**Comment by emilagervigstarup** [comment]
Can't get it to work.
It works without CKSIncrementalStore. With CKSIncrementalStore it only works until I restart the app.

**Comment by nofelmahmood** [comment]
I have checked. I think this is not a bug. I checked by changing the model with to one and a to many inverse relationship. I also tried re starting the demo app several times and changing values for to many and to one relationships. All worked fine. I have updated the demo btw. You can also try out it over there.
Please double check your CoreData model. [This](http://stackoverflow.com/questions/16711160/unacceptable-type-of-value-for-to-one-relationship-desired-type-nsmanagedobje) helped me too. Please also check that if you are using the same instance of NSManagedObjectContext to modify the objects.

**Comment by apoorvmote** [comment]
I downloaded the updated code & its crashing. Not working with following error 
CKSIncrementalStoreDemo.sqlite options:(null) ... returned error Error Domain=NSCocoaErrorDomain Code=134100 "The operation couldn’t be completed. (Cocoa error 134100.)"

**Comment by nofelmahmood** [comment]
@apoorvmote I cannot guide you through ios development. This error is not related to this project. Google it and please avoid posting these things here.

**Comment by apoorvmote** [comment]
Wow that's bit harsh. I was just about to delete my post because I found out that I didn't delete the app from the simulator before running new version. And your new code is working just fine.

**Comment by nofelmahmood** [comment]
Sorry for being harsh man ! I just wanted to guide you that the problems are on your own side. Please always google and check out stackoverflow before posting something here. If you find a real bug in this project I'l be there always. Sorry again :)

**Comment by nofelmahmood** [comment]
Sorry you were right this was a CKSIncrementalStore bug. Check the latest build now and post feedback here :)
